// <auto-generated />
using System;
using InventoryApp.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InventoryApp.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250517152359_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InventoryApp.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 5, 17, 15, 23, 59, 39, DateTimeKind.Utc).AddTicks(470),
                            Description = "High-precision optical sensor with 16000 DPI, ergonomic design, and RGB lighting",
                            Name = "Professional Gaming Mouse",
                            Price = 79.99m,
                            SKU = "MOUSE-PRO-001",
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2025, 5, 17, 15, 23, 59, 39, DateTimeKind.Utc).AddTicks(470)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 5, 17, 15, 23, 59, 39, DateTimeKind.Utc).AddTicks(470),
                            Description = "Cherry MX Blue switches, full RGB backlight, aluminum frame",
                            Name = "Mechanical Keyboard",
                            Price = 129.99m,
                            SKU = "KB-MECH-002",
                            StockQuantity = 30,
                            UpdatedAt = new DateTime(2025, 5, 17, 15, 23, 59, 39, DateTimeKind.Utc).AddTicks(470)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 5, 17, 15, 23, 59, 39, DateTimeKind.Utc).AddTicks(470),
                            Description = "27-inch 4K IPS display, 144Hz refresh rate, 1ms response time",
                            Name = "4K Gaming Monitor",
                            Price = 499.99m,
                            SKU = "MON-4K-003",
                            StockQuantity = 15,
                            UpdatedAt = new DateTime(2025, 5, 17, 15, 23, 59, 39, DateTimeKind.Utc).AddTicks(470)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 5, 17, 15, 23, 59, 39, DateTimeKind.Utc).AddTicks(470),
                            Description = "7.1 surround sound, noise-canceling mic, memory foam ear cushions",
                            Name = "Gaming Headset",
                            Price = 89.99m,
                            SKU = "HEAD-PRO-004",
                            StockQuantity = 40,
                            UpdatedAt = new DateTime(2025, 5, 17, 15, 23, 59, 39, DateTimeKind.Utc).AddTicks(470)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 5, 17, 15, 23, 59, 39, DateTimeKind.Utc).AddTicks(470),
                            Description = "Extended size mousepad with RGB border, anti-slip base",
                            Name = "RGB Mousepad XL",
                            Price = 29.99m,
                            SKU = "PAD-RGB-005",
                            StockQuantity = 60,
                            UpdatedAt = new DateTime(2025, 5, 17, 15, 23, 59, 39, DateTimeKind.Utc).AddTicks(470)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 5, 17, 15, 23, 59, 39, DateTimeKind.Utc).AddTicks(470),
                            Description = "Ergonomic design, adjustable armrests, lumbar support, PU leather",
                            Name = "Gaming Chair",
                            Price = 249.99m,
                            SKU = "CHAIR-PRO-006",
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2025, 5, 17, 15, 23, 59, 39, DateTimeKind.Utc).AddTicks(470)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 5, 17, 15, 23, 59, 39, DateTimeKind.Utc).AddTicks(470),
                            Description = "Professional condenser microphone, plug & play, cardioid pattern",
                            Name = "USB Microphone",
                            Price = 119.99m,
                            SKU = "MIC-USB-007",
                            StockQuantity = 25,
                            UpdatedAt = new DateTime(2025, 5, 17, 15, 23, 59, 39, DateTimeKind.Utc).AddTicks(470)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 5, 17, 15, 23, 59, 39, DateTimeKind.Utc).AddTicks(470),
                            Description = "8GB GDDR6, ray tracing, DLSS 3.0 support",
                            Name = "Graphics Card RTX 4060",
                            Price = 399.99m,
                            SKU = "GPU-4060-008",
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2025, 5, 17, 15, 23, 59, 39, DateTimeKind.Utc).AddTicks(470)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 5, 17, 15, 23, 59, 39, DateTimeKind.Utc).AddTicks(470),
                            Description = "Dual-band WiFi 6, gaming prioritization, 4 ethernet ports",
                            Name = "Gaming Router",
                            Price = 179.99m,
                            SKU = "NET-GAME-009",
                            StockQuantity = 35,
                            UpdatedAt = new DateTime(2025, 5, 17, 15, 23, 59, 39, DateTimeKind.Utc).AddTicks(470)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 5, 17, 15, 23, 59, 39, DateTimeKind.Utc).AddTicks(470),
                            Description = "15 LCD keys, customizable actions, live content creation control",
                            Name = "Streaming Deck",
                            Price = 149.99m,
                            SKU = "STREAM-PRO-010",
                            StockQuantity = 15,
                            UpdatedAt = new DateTime(2025, 5, 17, 15, 23, 59, 39, DateTimeKind.Utc).AddTicks(470)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
